[package]
edition = "2021"
name = "secq256k1"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.12.0"
hex-literal = {version = "0.3"}
k256 = "0.11.6"
num-bigint-dig = "0.8.2"
primeorder = {git = "https://github.com/DanTehrani/elliptic-curves.git", features = ["serde"]}
rand_core = {version = "0.6", default-features = false}
serde = {version = "1.0.106", features = ["derive"]}
zeroize = {version = "1", default-features = false}
