[package]
edition = "2021"
name = "hoplite_circuit"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dev-graph"]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dependencies]
bincode = "1.2.1"
circuit_reader = {path = "../circuit_reader"}
ff = "0.12.1"
halo2-base = {git = "https://github.com/axiom-crypto/halo2-lib.git", default-features = false, features = ["halo2-pse"]}
halo2-ecc = {git = "https://github.com/axiom-crypto/halo2-lib.git", default-features = false, features = ["halo2-pse"]}
halo2_proofs = {git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_01_20"}
hoplite = {path = "../hoplite"}
num-bigint = {version = "0.4", features = ["rand"]}
num-traits = "0.2.15"
plotters = {version = "0.3.0", optional = true}
rand_core = {version = "0.6", default-features = false, features = ["getrandom"]}
secpq_curves = {git = "https://github.com/DanTehrani/secpq_curves.git"}
secq256k1 = {path = "../secq256k1"}
serde = {version = "1.0.106", features = ["derive"]}
spartan = {path = "../Spartan-secq"}
tabbycat = {version = "0.1", features = ["attributes"], optional = true}

[dev-dependencies]
ark-std = {version = "0.3.0", features = ["print-trace"]}
